# Generated by Django 5.2.6 on 2025-09-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Professional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("street", models.CharField(max_length=255)),
                ("number", models.CharField(max_length=20)),
                ("complement", models.CharField(blank=True, max_length=50, null=True)),
                ("neighborhood", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("state", models.CharField(max_length=2)),
                ("zipcode", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=255, verbose_name="Nome Social")),
                (
                    "profession",
                    models.CharField(
                        choices=[
                            ("CLINICO_GERAL", "Clínico Geral"),
                            ("DERMATOLOGISTA", "Dermatologista"),
                            ("GINECOLOGISTA", "Ginecologista"),
                            ("PEDIATRA", "Pediatra"),
                            ("CARDIOLOGISTA", "Cardiologista"),
                            ("PSICOLOGO", "Psicólogo"),
                            ("ORTOPEDISTA", "Ortopedista"),
                            ("ENDOCRINOLOGISTA", "Endocrinologista"),
                            ("NEUROLOGISTA", "Neurologista"),
                            ("DENTISTA", "Dentista"),
                        ],
                        max_length=50,
                        verbose_name="Profissão",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Telefone"
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
