# Generated by Django 5.2.6 on 2025-09-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("professionals", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="professional",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="professional",
            name="phone",
            field=models.CharField(max_length=20, verbose_name="Telefone"),
        ),
    ]
