name: Django CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.13]

    services:
      postgres:
        image: postgres:14.19
        env:
          POSTGRES_DB: github_actions
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
        - 5432:5432

        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install Poetry
      run: pip install poetry

    - name: Install dependencies
      run: poetry install --with dev --no-root
        
    - name: Lint with Black
      run: poetry run black . --check

    - name: Sort imports with isort
      run: poetry run isort . --check-only

    - name: Check code with Flake8
      run: poetry run flake8 .

 
    - name: Run migrations
      env:
        DJANGO_ENV: development
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        POSTGRES_DB: github_actions
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_HOST: localhost
        POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }} # get randomly assigned published port
      run: poetry run python manage.py migrate
      
    - name: Run Django tests
      env:
        DJANGO_ENV: development
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        POSTGRES_DB: github_actions
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_HOST: localhost
        POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }} # get randomly assigned published port
      run: poetry run python manage.py test
  
  deploy:
    name: Build and Deploy to Elastic Beanstalk
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    env:
      DOCKER_IMAGE: juliavillela/lacrei-saude-app

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Build and push image to Docker Hub
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image (multi-arch)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE }}:${{ github.sha }}
            ${{ env.DOCKER_IMAGE }}:latest

      # Prepare Dockerrun bundle
      - name: Pin image tag in Dockerrun.aws.json
        run: |
          sudo apt-get update && sudo apt-get install -y jq
          IMG="${DOCKER_IMAGE}:${GITHUB_SHA}"
          # Dockerrun v1 (single container) expected
          jq --arg img "$IMG" '.Image.Name=$img' Dockerrun.aws.json > Dockerrun.generated.json
          mv Dockerrun.generated.json Dockerrun.aws.json
          echo "Pinned to $IMG"
          cat Dockerrun.aws.json

      - name: Create EB bundle zip
        run: |
          zip -r deploy.zip Dockerrun.aws.json .platform -x "**/.DS_Store"

      # Deploy to Elastic Beanstalk
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ secrets.AWS_REGION }}

      - name: Upload to S3 and deploy to EB
        env:
          EB_APPLICATION_NAME: ${{ secrets.EB_APPLICATION_NAME }}
          EB_ENVIRONMENT_NAME: ${{ secrets.EB_ENVIRONMENT_NAME }}
          S3_BUCKET:           ${{ secrets.S3_BUCKET }}
        run: |
          set -euo pipefail
          VERSION_LABEL="${GITHUB_SHA::8}-$(date +%Y%m%d%H%M%S)"
          S3_KEY="eb/${VERSION_LABEL}/deploy.zip"

          echo "Uploading deploy.zip to s3://${S3_BUCKET}/${S3_KEY}"
          aws s3 cp deploy.zip "s3://${S3_BUCKET}/${S3_KEY}"

          echo "Creating EB application version: ${VERSION_LABEL}"
          aws elasticbeanstalk create-application-version \
            --application-name "${EB_APPLICATION_NAME}" \
            --version-label "${VERSION_LABEL}" \
            --source-bundle S3Bucket="${S3_BUCKET}",S3Key="${S3_KEY}"

          echo "Updating environment ${EB_ENVIRONMENT_NAME} to ${VERSION_LABEL}"
          aws elasticbeanstalk update-environment \
            --environment-name "${EB_ENVIRONMENT_NAME}" \
            --version-label "${VERSION_LABEL}"